import type ProductType from "../types/ProductType";

export const DEFUALT_PRODUCT_DATA: ProductType[] = [
  {
    ID: 1,
    Name: "Lumixia Smart Bulb",
    Description:
      "Wi-Fi enabled LED bulb with 16 million colors and voice control.",
    Price: 24.99,
    ImageURL:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQLhYL5T4L9EqKe2a3CK1jjRo29y23-0cwEkA&s"},
  {
    ID: 2,
    Name: "SonicWave Headphones",
    Description:
      "Active noise-canceling over-ear headphones with 40-hour battery life.",
    Price: 199.0,
    ImageURL:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQLhYL5T4L9EqKe2a3CK1jjRo29y23-0cwEkA&s"},
  {
    ID: 3,
    Name: "AeroStream Desk Fan",
    Description: "Bladeless ultra-quiet desk fan with 10 speed settings.",
    Price: 85.5,
    ImageURL:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQLhYL5T4L9EqKe2a3CK1jjRo29y23-0cwEkA&s"},
  {
    ID: 4,
    Name: "Terra-Firm Yoga Mat",
    Description: "Eco-friendly non-slip rubber mat with alignment markers.",
    Price: 45.0,
    ImageURL:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQLhYL5T4L9EqKe2a3CK1jjRo29y23-0cwEkA&s"},
  {
    ID: 5,
    Name: "HydraPeak Flask",
    Description: "Vacuum-insulated stainless steel water bottle (32oz).",
    Price: 29.95,
    ImageURL:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQLhYL5T4L9EqKe2a3CK1jjRo29y23-0cwEkA&s"},
  {
    ID: 6,
    Name: "Zenith Mechanical Keyboard",
    Description: "RGB backlit tactile switches with a compact 75% layout.",
    Price: 120.0,
    ImageURL:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQLhYL5T4L9EqKe2a3CK1jjRo29y23-0cwEkA&s"},
  {
    ID: 7,
    Name: "PixelView Monitor",
    Description: "27-inch 4K UHD IPS display with HDR400 support.",
    Price: 349.99,
    ImageURL:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQLhYL5T4L9EqKe2a3CK1jjRo29y23-0cwEkA&s"},
  {
    ID: 8,
    Name: "SwiftGlide Mouse",
    Description: "Ergonomic wireless gaming mouse with 26k DPI sensor.",
    Price: 69.99,
    ImageURL:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQLhYL5T4L9EqKe2a3CK1jjRo29y23-0cwEkA&s"},
  {
    ID: 9,
    Name: "NovaCharge Power Bank",
    Description: "20,000mAh portable charger with USB-C PD fast charging.",
    Price: 49.0,
    ImageURL:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQLhYL5T4L9EqKe2a3CK1jjRo29y23-0cwEkA&s"},
  {
    ID: 10,
    Name: "Orbit Smart Watch",
    Description: "Fitness tracker with heart rate monitor and GPS tracking.",
    Price: 159.0,
    ImageURL:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQLhYL5T4L9EqKe2a3CK1jjRo29y23-0cwEkA&s"},
  {
    ID: 11,
    Name: "Bistro Brew Coffee Maker",
    Description: "Programmable drip coffee machine with built-in grinder.",
    Price: 129.99,
    ImageURL:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQLhYL5T4L9EqKe2a3CK1jjRo29y23-0cwEkA&s"},
  {
    ID: 12,
    Name: "EmberGlow Space Heater",
    Description: "Ceramic portable heater with digital thermostat and remote.",
    Price: 74.5,
    ImageURL:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQLhYL5T4L9EqKe2a3CK1jjRo29y23-0cwEkA&s"},
  {
    ID: 13,
    Name: "Titanium Chef Knife",
    Description: "8-inch forged high-carbon steel blade with ergonomic handle.",
    Price: 88.0,
    ImageURL:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQLhYL5T4L9EqKe2a3CK1jjRo29y23-0cwEkA&s"},
  {
    ID: 14,
    Name: "CloudPuff Pillow",
    Description:
      "Adjustable shredded memory foam pillow for all sleep positions.",
    Price: 35.0,
    ImageURL:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQLhYL5T4L9EqKe2a3CK1jjRo29y23-0cwEkA&s"},
  {
    ID: 15,
    Name: "Velocita Router",
    Description: "WiFi 6 Dual-Band Mesh Router for seamless home coverage.",
    Price: 180.0,
    ImageURL:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQLhYL5T4L9EqKe2a3CK1jjRo29y23-0cwEkA&s"},
  {
    ID: 16,
    Name: "GlowFlow Humidifier",
    Description: "Ultrasonic cool mist humidifier with essential oil diffuser.",
    Price: 39.99,
    ImageURL:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQLhYL5T4L9EqKe2a3CK1jjRo29y23-0cwEkA&s"},
  {
    ID: 17,
    Name: "PeakPulse Fitness Bike",
    Description: "Indoor stationary bike with 12-inch touchscreen display.",
    Price: 899.0,
    ImageURL:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQLhYL5T4L9EqKe2a3CK1jjRo29y23-0cwEkA&s"},
  {
    ID: 18,
    Name: "DuraStep Hiking Boots",
    Description: "Waterproof, breathable trail boots with Vibram soles.",
    Price: 145.0,
    ImageURL:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQLhYL5T4L9EqKe2a3CK1jjRo29y23-0cwEkA&s"},
  {
    ID: 19,
    Name: "PureAir Purifier",
    Description: "HEPA H13 air purifier for rooms up to 500 sq ft.",
    Price: 119.99,
    ImageURL:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQLhYL5T4L9EqKe2a3CK1jjRo29y23-0cwEkA&s"},
  {
    ID: 20,
    Name: "Kinetix Jump Rope",
    Description: "Digital weighted jump rope with calorie counter.",
    Price: 19.99,
    ImageURL:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQLhYL5T4L9EqKe2a3CK1jjRo29y23-0cwEkA&s"},
  {
    ID: 21,
    Name: "Luxor Leather Wallet",
    Description: "RFID blocking bi-fold wallet made from Italian leather.",
    Price: 55.0,
    ImageURL:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQLhYL5T4L9EqKe2a3CK1jjRo29y23-0cwEkA&s"},
  {
    ID: 22,
    Name: "Astra Telescope",
    Description: "Reflector telescope for beginners with smartphone adapter.",
    Price: 210.0,
    ImageURL:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQLhYL5T4L9EqKe2a3CK1jjRo29y23-0cwEkA&s"},
  {
    ID: 23,
    Name: "SlatePad Tablet",
    Description: "10-inch Android tablet with octa-core processor and stylus.",
    Price: 249.0,
    ImageURL:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQLhYL5T4L9EqKe2a3CK1jjRo29y23-0cwEkA&s"},
  {
    ID: 24,
    Name: "VoltDash Electric Scooter",
    Description: "Foldable commuter scooter with 20mph top speed.",
    Price: 450.0,
    ImageURL:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQLhYL5T4L9EqKe2a3CK1jjRo29y23-0cwEkA&s"},
  {
    ID: 25,
    Name: "AquaLens Action Cam",
    Description: "4K waterproof camera with image stabilization.",
    Price: 135.0,
    ImageURL:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQLhYL5T4L9EqKe2a3CK1jjRo29y23-0cwEkA&s"},
  {
    ID: 26,
    Name: "Solaris Solar Panel",
    Description: "100W foldable solar charger for camping and emergencies.",
    Price: 160.0,
    ImageURL:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQLhYL5T4L9EqKe2a3CK1jjRo29y23-0cwEkA&s"},
  {
    ID: 27,
    Name: "SoundBar Pro",
    Description:
      "3.1 channel soundbar with wireless subwoofer and Dolby Atmos.",
    Price: 299.99,
    ImageURL:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQLhYL5T4L9EqKe2a3CK1jjRo29y23-0cwEkA&s"},
  {
    ID: 28,
    Name: "EverWrite Smart Pen",
    Description: "Digitizes handwritten notes to your phone in real-time.",
    Price: 99.0,
    ImageURL:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQLhYL5T4L9EqKe2a3CK1jjRo29y23-0cwEkA&s"},
  {
    ID: 29,
    Name: "Voyager Backpack",
    Description: "Anti-theft travel backpack with hidden laptop compartment.",
    Price: 78.0,
    ImageURL:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQLhYL5T4L9EqKe2a3CK1jjRo29y23-0cwEkA&s"},
  {
    ID: 30,
    Name: "CoreBalance Ball",
    Description: "Professional grade stability ball for core workouts.",
    Price: 25.0,
    ImageURL:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQLhYL5T4L9EqKe2a3CK1jjRo29y23-0cwEkA&s"},
  {
    ID: 31,
    Name: "GrillMaster BBQ Kit",
    Description: "20-piece stainless steel tool set with carrying case.",
    Price: 62.99,
    ImageURL:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQLhYL5T4L9EqKe2a3CK1jjRo29y23-0cwEkA&s"},
  {
    ID: 32,
    Name: "NightOwl Security Cam",
    Description: "Outdoor security camera with color night vision and siren.",
    Price: 89.0,
    ImageURL:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQLhYL5T4L9EqKe2a3CK1jjRo29y23-0cwEkA&s"},
  {
    ID: 33,
    Name: "FrostBox Cooler",
    Description: "Heavy-duty rotomolded cooler that keeps ice for 5 days.",
    Price: 175.0,
    ImageURL:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQLhYL5T4L9EqKe2a3CK1jjRo29y23-0cwEkA&s"},
  {
    ID: 34,
    Name: "Nebula Projector",
    Description: "Portable mini projector with 1080p support and speakers.",
    Price: 220.0,
    ImageURL:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQLhYL5T4L9EqKe2a3CK1jjRo29y23-0cwEkA&s"},
  {
    ID: 35,
    Name: "VitalScale Smart Scale",
    Description: "Body composition scale measuring body fat, BMI, and muscle.",
    Price: 45.99,
    ImageURL:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQLhYL5T4L9EqKe2a3CK1jjRo29y23-0cwEkA&s"},
  {
    ID: 36,
    Name: "PetSpy Treat Dispenser",
    Description: "WiFi pet camera that lets you toss treats remotely.",
    Price: 149.0,
    ImageURL:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQLhYL5T4L9EqKe2a3CK1jjRo29y23-0cwEkA&s"},
  {
    ID: 37,
    Name: "CleanSweep Robotic Vacuum",
    Description: "Lidar-guided vacuum and mop with auto-empty station.",
    Price: 499.0,
    ImageURL:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQLhYL5T4L9EqKe2a3CK1jjRo29y23-0cwEkA&s"},
  {
    ID: 38,
    Name: "FlexiStand Desk",
    Description: "Electric height-adjustable standing desk frame.",
    Price: 320.0,
    ImageURL:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQLhYL5T4L9EqKe2a3CK1jjRo29y23-0cwEkA&s"},
  {
    ID: 39,
    Name: "Oasis Desk Fountain",
    Description: "Tabletop water fountain with LED lighting and river rocks.",
    Price: 32.5,
    ImageURL:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQLhYL5T4L9EqKe2a3CK1jjRo29y23-0cwEkA&s"},
  {
    ID: 40,
    Name: "ThunderBolt SSD",
    Description: "1TB external NVMe SSD with 2000MB/s read speeds.",
    Price: 115.0,
    ImageURL:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQLhYL5T4L9EqKe2a3CK1jjRo29y23-0cwEkA&s"},
  {
    ID: 41,
    Name: "ZenGarden Bonsai Kit",
    Description: "Complete kit to grow and prune your own Juniper tree.",
    Price: 38.0,
    ImageURL:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQLhYL5T4L9EqKe2a3CK1jjRo29y23-0cwEkA&s"},
  {
    ID: 42,
    Name: "EcoClick Rechargeable Battery",
    Description: "Pack of 8 AA batteries with USB-C charging ports.",
    Price: 28.0,
    ImageURL:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQLhYL5T4L9EqKe2a3CK1jjRo29y23-0cwEkA&s"},
  {
    ID: 43,
    Name: "VividPen Graphic Tablet",
    Description: "Pressure-sensitive drawing tablet for digital artists.",
    Price: 59.99,
    ImageURL:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQLhYL5T4L9EqKe2a3CK1jjRo29y23-0cwEkA&s"},
  {
    ID: 44,
    Name: "SkyGlide Drone",
    Description: "4K camera drone with 30-minute flight time and GPS.",
    Price: 380.0,
    ImageURL:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQLhYL5T4L9EqKe2a3CK1jjRo29y23-0cwEkA&s"},
  {
    ID: 45,
    Name: "IronClad Cast Iron Skillet",
    Description: "12-inch pre-seasoned heavy-duty cast iron pan.",
    Price: 42.0,
    ImageURL:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQLhYL5T4L9EqKe2a3CK1jjRo29y23-0cwEkA&s"},
  {
    ID: 46,
    Name: "MobiMount Car Holder",
    Description: "Magnetic dashboard mount for all smartphone models.",
    Price: 18.5,
    ImageURL:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQLhYL5T4L9EqKe2a3CK1jjRo29y23-0cwEkA&s"},
  {
    ID: 47,
    Name: "SleepSync Eye Mask",
    Description: "Bluetooth-enabled sleep mask with integrated speakers.",
    Price: 34.99,
    ImageURL:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQLhYL5T4L9EqKe2a3CK1jjRo29y23-0cwEkA&s"},
  {
    ID: 48,
    Name: "PulsePro Massage Gun",
    Description: "Percussive therapy device for deep tissue muscle relief.",
    Price: 110.0,
    ImageURL:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQLhYL5T4L9EqKe2a3CK1jjRo29y23-0cwEkA&s"},
  {
    ID: 49,
    Name: "Trekker Hammock",
    Description: "Double nylon camping hammock with tree straps.",
    Price: 39.0,
    ImageURL:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQLhYL5T4L9EqKe2a3CK1jjRo29y23-0cwEkA&s"},
  {
    ID: 50,
    Name: "FocusFlow Hourglass",
    Description: "Hand-blown sand timer (60 minutes) for productivity.",
    Price: 22.99,
    ImageURL:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQLhYL5T4L9EqKe2a3CK1jjRo29y23-0cwEkA&s"},
];
